Repository Team-MindWay/MindWay-v2-iOS, pull requests merged in 2024-06, with the labels that each got.

#82 🔀 :: [#78] GauthSignin 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  App/Sources/Application/MindWayApp.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/Extensions/View+eraseToAnyView.swift
  App/Sources/Feature/BaseFeature/BaseViewModel.swift
  App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
  App/Sources/Feature/BaseFeature/Flow/TabFlow.swift
  App/Sources/Feature/BaseFeature/Sources/SceneState.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
  App/Sources/Feature/MainFeature/MainComponent.swift
  App/Sources/Feature/MainFeature/MainFactory.swift
  App/Sources/Feature/RootFeature/RootComponent.swift
  App/Sources/Feature/RootFeature/RootView.swift
  App/Sources/Feature/SigninFeature/Component/GAuthButtonView.swift
  App/Sources/Feature/SigninFeature/Interface/SigninFactory.swift
  App/Sources/Feature/SigninFeature/Sources/SigninComponent.swift
  App/Sources/Feature/SigninFeature/Sources/SigninView.swift
  App/Sources/Feature/SigninFeature/Sources/SigninViewModel.swift
  App/Support/Info.plist
  Scripts/NeedleRunScript.sh
  Scripts/Setup.sh
  Service/Project.swift
  Service/Sources/Base/API/RefreshAPI.swift
  Service/Sources/Base/DataSoueces/BaseRemoteDataSource.swift
  Service/Sources/Base/Enum/UserAuthorityType.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Response/SigninResponseDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/LocalAuthDataSourceImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSourceImpl.swift
  Service/Sources/Domain/AuthDomain/Entity/UserSignupInfoEntity.swift
  Service/Sources/Domain/AuthDomain/Error/AuthDomainError.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepositoryImpl.swift
  Service/Sources/Domain/AuthDomain/UseCase/LoginUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/UseCase/LogoutUseCaseImpl.swift
  Service/Sources/Interface/DataSource/Auth/LocalAuthDataSource.swift
  Service/Sources/Interface/DataSource/Auth/RemoteAuthDateSource.swift
  Service/Sources/Interface/Repository/Auth/AuthRepository.swift
  Service/Sources/Interface/UseCase/Auth/LoginUseCase.swift
  Service/Sources/Interface/UseCase/Auth/LogoutUseCase.swift
  ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  XCConfig/Shared.xcconfig
Labels: ✨Feature, ⚙️Setting, 0️⃣Priority: Critical

#88 🔀 :: rank 도메인 세팅
  Service/Sources/Base/MindWayAPI.swift
  Service/Sources/Domain/RankDomain/API/RankAPI.swift
  Service/Sources/Domain/RankDomain/DTO/Response/FetchRankInfoResponseDTO.swift
  Service/Sources/Domain/RankDomain/DataSource/RemoteRankDataSourceImpl.swift
  Service/Sources/Domain/RankDomain/Entity/RankInfoEntity.swift
  Service/Sources/Domain/RankDomain/Error/RankDomainError.swift
  Service/Sources/Domain/RankDomain/Repository/RankRepositoryImpl.swift
  Service/Sources/Domain/RankDomain/UseCase/FetchRankInfoUseCaseImpl.swift
  Service/Sources/Interface/DataSource/Rank/RemoteRankDataSource.swift
  Service/Sources/Interface/Repository/Rank/RankRepository.swift
  Service/Sources/Interface/UseCase/Rank/FetchRankInfoUseCase.swift
Labels: 1️⃣Priority: High, ✨Feature

#89 🔀 :: goal 도메인 세팅
  Service/Sources/Domain/GoalDomain/API/GoalAPI.swift
  Service/Sources/Domain/GoalDomain/DTO/Response/FetchGoalInfoResponseDTO.swift
  Service/Sources/Domain/GoalDomain/DataSource/RemoteGoalDataSourceImpl.swift
  Service/Sources/Domain/GoalDomain/Entity/GoalInfoEntity.swift
  Service/Sources/Domain/GoalDomain/Error/GoalDomainError.swift
  Service/Sources/Domain/GoalDomain/Repository/GoalRepositoryImpl.swift
  Service/Sources/Domain/GoalDomain/UseCase/FetchGoalUseCaseImpl.swift
  Service/Sources/Domain/GoalDomain/UseCase/SettingGoalUseCaseImpl.swift
  Service/Sources/Interface/DTO/Request/SettingGoalRequestDTO.swift
  Service/Sources/Interface/DataSource/Goal/RemoteGoalDataSource.swift
  Service/Sources/Interface/Repository/Goal/GoalRepository.swift
  Service/Sources/Interface/UseCase/Goal/FetchGoalUseCase.swift
  Service/Sources/Interface/UseCase/Goal/SettingGoalUseCase.swift
Labels: 1️⃣Priority: High, ✨Feature

#90 🔀 :: book 도메인 세팅
  Service/Sources/Domain/BookDomain/API/BookAPI.swift
  Service/Sources/Domain/BookDomain/DTO/Response/FetchBookDetailInfoResponseDTO.swift
  Service/Sources/Domain/BookDomain/DTO/Response/FetchBookInfoResponseDTO.swift
  Service/Sources/Domain/BookDomain/DataSource/RemoteBookDataSourceImpl.swift
  Service/Sources/Domain/BookDomain/Entity/BookDetailInfoEntity.swift
  Service/Sources/Domain/BookDomain/Entity/BookInfoEntity.swift
  Service/Sources/Domain/BookDomain/Error/BookDomainError.swift
  Service/Sources/Domain/BookDomain/Repository/BookRepositoryImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/DeleteBookUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/FetchBookDetailUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/FetchBookListUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/ModifyBookUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/WriteBookUseCaseImpl.swift
  Service/Sources/Domain/GoalDomain/UseCase/SettingGoalUseCaseImpl.swift
  Service/Sources/Interface/DTO/Book/Request/BookInfoRequestDTO.swift
  Service/Sources/Interface/DTO/Goal/Request/SettingGoalRequestDTO.swift
  Service/Sources/Interface/DataSource/Book/RemoteBookDataSource.swift
  Service/Sources/Interface/Repository/Book/BookRepository.swift
  Service/Sources/Interface/UseCase/Book/DeleteBookUseCase.swift
  Service/Sources/Interface/UseCase/Book/FetchBookDetailUseCase.swift
  Service/Sources/Interface/UseCase/Book/FetchBookListUseCase.swift
  Service/Sources/Interface/UseCase/Book/ModifyBookUseCase.swift
  Service/Sources/Interface/UseCase/Book/WriteBookUseCase.swift
  Service/Sources/Interface/UseCase/Goal/SettingGoalUseCase.swift
Labels: 1️⃣Priority: High, ✨Feature

#91 🔀 :: [#87] OrderDomain Setting
  Service/Sources/Domain/OrderDomain/API/OrderAPI.swift
  Service/Sources/Domain/OrderDomain/DTO/Request/OrderBookRequestDTO.swift
  Service/Sources/Domain/OrderDomain/DTO/Request/UpdateBookRequestDTO.swift
  Service/Sources/Domain/OrderDomain/DataSource/RemoteOrderDataSourceImpl.swift
  Service/Sources/Domain/OrderDomain/Entity/OrderEntity.swift
  Service/Sources/Domain/OrderDomain/Error/OrderDomainError.swift
  Service/Sources/Domain/OrderDomain/Repository/OrderRepositoryImpl.swift
  Service/Sources/Domain/OrderDomain/UseCase/DeleteOrderUseCaseImpl.swift
  Service/Sources/Domain/OrderDomain/UseCase/OrderBookUseCaseImpl.swift
  Service/Sources/Domain/OrderDomain/UseCase/UpdateOrderUseCaseImpl.swift
  Service/Sources/Interface/DataSource/Order/RemoteOrderDataSource.swift
  Service/Sources/Interface/Repository/Order/OrderRepository.swift
  Service/Sources/Interface/UseCase/Order/DeleteOrderUseCase.swift
  Service/Sources/Interface/UseCase/Order/OrderBookUseCase.swift
  Service/Sources/Interface/UseCase/Order/UpdateOrderUseCase.swift
Labels: ⚙️Setting, 0️⃣Priority: Critical

#95 🔀 :: [#94] NoticeDomain Setting
  Service/Sources/Base/MindWayAPI.swift
  Service/Sources/Domain/BookDomain/DTO/Response/FetchBookDetailInfoResponseDTO.swift
  Service/Sources/Domain/BookDomain/Repository/BookRepositoryImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/DeleteBookUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/FetchBookDetailUseCaseImpl.swift
  Service/Sources/Domain/BookDomain/UseCase/ModifyBookUseCaseImpl.swift
  Service/Sources/Domain/NoticeDomain/API/NoticeAPI.swift
  Service/Sources/Domain/NoticeDomain/DTO/Response/FetchNoticeResponseDTO.swift
  Service/Sources/Domain/NoticeDomain/DataSource/RemoteNoticeDataSourceImpl.swift
  Service/Sources/Domain/NoticeDomain/Entity/FetchNoticeEntity.swift
  Service/Sources/Domain/NoticeDomain/Error/NoticeDomainError.swift
  Service/Sources/Domain/NoticeDomain/Repository/NoticeRepositoryImpl.swift
  Service/Sources/Domain/NoticeDomain/UseCase/FetchNoticeUseCaseImpl.swift
  Service/Sources/Interface/DataSource/Notice/RemoteNoticeDataSource.swift
  Service/Sources/Interface/Repository/Notice/NoticeRepository.swift
  Service/Sources/Interface/UseCase/Notice/FetchNoticeUseCase.swift
Labels: ⚙️Setting, 0️⃣Priority: Critical
