Repository Team-MindWay/MindWay-v2-iOS, pull requests merged in 2024-04, with the labels that each got.

#18 🔀 :: [#12] SplashView 추가
  App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  App/Resources/Assets.xcassets/Contents.json
  App/Resources/Image/Images.xcassets/Contents.json
  App/Resources/Image/Images.xcassets/MindWay.imageset/Contents.json
  App/Resources/Image/Images.xcassets/MindWay.imageset/MindWay.png
  App/Sources/Application/MindWayApp.swift
  App/Sources/Feature/SplashFeature/SplashView.swift
Labels: ✨Feature, 0️⃣Priority: Critical

#20 PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨Feature, 0️⃣Priority: Critical

#21 🔀 :: [#15] DesignSystem에 TextField 추가
  App/Sources/DesignSystem/TextField/MindWayTextField.swift
Labels: ✨Feature, 0️⃣Priority: Critical

#19 🔀 :: [#14] DesignSystem에 버튼 추가
  App/Resources/Color/ButtonPushed.xcassets/Color.colorset/Contents.json
  App/Resources/Color/ButtonPushed.xcassets/Contents.json
  App/Sources/DesignSystem/Button/MindWayButton.swift
  App/Sources/DesignSystem/Button/MindWayButtonStyle.swift
  App/Sources/DesignSystem/Color/Color+MindWay.swift
  App/Sources/DesignSystem/Color/MindWayColorSystem+ButtonPushed.swift
  App/Sources/DesignSystem/Extensions/View+buttonwrapper.swift
Labels: ✨Feature, 0️⃣Priority: Critical

#25 🔀 :: [#23] LoginPage 퍼블리싱
  App/Resources/Color/ButtonPushed.xcassets/ButtonPushed.colorset/Contents.json
  App/Resources/Image/Images.xcassets/GauthLogo.imageset/Contents.json
  App/Resources/Image/Images.xcassets/GauthLogo.imageset/Vector.svg
  App/Resources/Image/Images.xcassets/SignIn.imageset/Contents.json
  App/Resources/Image/Images.xcassets/SignIn.imageset/GAuthLogo.svg
  App/Sources/DesignSystem/Button/MindWayButtonStyle.swift
  App/Sources/DesignSystem/Color/MindWayColorSystem+ButtonPushed.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#26 🔀 :: MainPage 퍼블리싱
  App/Resources/Icon/Icons.xcassets/Contents.json
  App/Resources/Icon/Icons.xcassets/MindWay_Logo.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/MindWay_Logo.imageset/MindWay_Logo.svg
  App/Resources/Icon/Icons.xcassets/megaphone.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/megaphone.imageset/megaphone.svg
  App/Sources/DesignSystem/Font/MindWayFontSystem+regular.swift
  App/Sources/DesignSystem/Font/MindWayFontSystem+semibold.swift
  App/Sources/Feature/MainFeature/MainView.swift
  App/Sources/Feature/SplashFeature/SplashView.swift
Labels: 1️⃣Priority: High, ✨Feature

#29 🔀 :: Icon 추가
  App/Resources/Icon/Icons.xcassets/Edit.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/Edit.imageset/Edit.svg
  App/Resources/Icon/Icons.xcassets/Exclamationmark.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/Exclamationmark.imageset/Exclamationmark.svg
  App/Resources/Icon/Icons.xcassets/Trash.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/Trash.imageset/Trash.svg
  App/Resources/Icon/Icons.xcassets/add_black.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/add_black.imageset/add_black.svg
  App/Resources/Icon/Icons.xcassets/add_main.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/add_main.imageset/add_main.svg
  App/Resources/Icon/Icons.xcassets/book.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/book.imageset/book.svg
  App/Resources/Icon/Icons.xcassets/book_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/book_fill.imageset/book_fill.svg
  App/Resources/Icon/Icons.xcassets/chevron-down.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/chevron-down.imageset/chevron-down.svg
  App/Resources/Icon/Icons.xcassets/chevron-left.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/chevron-left.imageset/chevron-left.svg
  App/Resources/Icon/Icons.xcassets/chevron-right.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/chevron-right.imageset/chevron-right.svg
  App/Resources/Icon/Icons.xcassets/chevron-top.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/chevron-top.imageset/chevron-top.svg
  App/Resources/Icon/Icons.xcassets/fail.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/fail.imageset/fail.svg
  App/Resources/Icon/Icons.xcassets/heart.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/heart.imageset/heart.svg
  App/Resources/Icon/Icons.xcassets/heart_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/heart_fill.imageset/heart_fill.svg
  App/Resources/Icon/Icons.xcassets/home.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/home.imageset/home.svg
  App/Resources/Icon/Icons.xcassets/home_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/home_fill.imageset/home_fill.svg
  App/Resources/Icon/Icons.xcassets/profile.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/profile.imageset/profile.svg
  App/Resources/Icon/Icons.xcassets/profile_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/profile_fill.imageset/profile_fill.svg
  App/Resources/Icon/Icons.xcassets/seeMore.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/seeMore.imageset/seeMore.svg
  App/Resources/Icon/Icons.xcassets/success.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/success.imageset/success.svg
Labels: ✨Feature, 0️⃣Priority: Critical

#31 🔀 :: DesignSystem에 BottomSheet 추가
  App/Sources/DesignSystem/BottomSheet/MindWayBottomSheet.swift
  App/Sources/DesignSystem/Extensions/Environment+safeAreaInsets.swift
  App/Sources/DesignSystem/Extensions/VIew+cornerRadius.swift
Labels: ✨Feature, 0️⃣Priority: Critical

#34 🔀 :: EventPage Publishing - xixn2
  App/Resources/Image/Images.xcassets/Book.imageset/Book.svg
  App/Resources/Image/Images.xcassets/Book.imageset/Contents.json
  App/Resources/Image/Images.xcassets/EventDetailIMG.imageset/Contents.json
  App/Resources/Image/Images.xcassets/EventDetailIMG.imageset/EventDetailIMG.svg
  App/Resources/Image/Images.xcassets/EventNoneIMG.imageset/Contents.json
  App/Resources/Image/Images.xcassets/EventNoneIMG.imageset/EventNoneIMG.svg
  App/Resources/Image/Images.xcassets/MindWayCheckGreen.imageset/MindWayOkImg.svg
  App/Resources/Image/Images.xcassets/MindWayCheckRed.imageset/fail.svg
  App/Sources/DesignSystem/Color/MindWayColorSystem+ButtonPushed.swift
  App/Sources/Feature/EventFeature/EventDetailView.swift
  App/Sources/Feature/EventFeature/EventTopBarView.swift
  App/Sources/Feature/EventFeature/EventViewModel.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#37 🔀 :: [#35] buttonPushed -> buttonpushed, gauthLogo -> gAuthLogo로 변경
  App/Resources/Color/ButtonPushed.xcassets/Contents.json
  App/Resources/Color/Main.xcassets/BUTTONPUSHED.colorset/Contents.json
  App/Sources/DesignSystem/Button/MindWayButtonStyle.swift
  App/Sources/DesignSystem/Color/Color+MindWay.swift
  App/Sources/DesignSystem/Color/MindWayColorSystem+ButtonPushed.swift
  App/Sources/DesignSystem/Color/MindWayColorSystem+Main.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
Labels: 0️⃣Priority: Critical, ⚡️Simple

#39 🔀 :: [#38] buttonpushed -> main으로 수정
  App/Sources/DesignSystem/Button/MindWayButtonStyle.swift
Labels: 3️⃣Priority: Low, ⚡️Simple

#41 🔀 :: 목표도서량 설정 페이지 퍼블리싱
  App/Sources/DesignSystem/Button/MindWayButton.swift
  App/Sources/Feature/GoalReadingFeature/Component/GoalReadingSettingTextField.swift
  App/Sources/Feature/GoalReadingFeature/Component/SettingGoalReadingView.swift
  App/Sources/Feature/GoalReadingFeature/GoalReadingView.swift
  App/Sources/Feature/GoalReadingFeature/VIewModel/GoalReadingViewModel.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
  App/Sources/Feature/MainFeature/SettingGoalReadingView.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#43 🔀 :: designsystem에 backbutton 추가
  App/Sources/DesignSystem/Extensions/View+MindWayBackButton.swift
  App/Sources/Feature/EventFeature/EventDetailView.swift
  App/Sources/Feature/GoalReadingFeature/GoalReadingView.swift
Labels: 1️⃣Priority: High, ✨Feature, 🎨Publishing

#45 🔀 :: [#33] bookpage 퍼블리싱
  App/Sources/Feature/BookFeature/BookRecommendView.swift
  App/Sources/Feature/BookFeature/Component/RecommendBook.swift
Labels: ✨Feature, 0️⃣Priority: Critical

#49 🐛 :: 상단 네비게이션바 길이수정
  App/Sources/Feature/EventFeature/EventTopBarView.swift
Labels: 🐛Bug, 0️⃣Priority: Critical

#52 gitignore 업데이트
  .gitignore
Labels: ⚙️Setting, 0️⃣Priority: Critical

#55 🔀 :: [#54] BookOrderPage 퍼블리싱
  App/Sources/DesignSystem/TextField/MindWayTextField.swift
  App/Sources/Feature/BookFeature/BookRecommendView.swift
  App/Sources/Feature/BookFeature/Component/RecommendBook.swift
  App/Sources/Feature/BookOrderFeature/BookOrderView.swift
  App/Sources/Feature/BookOrderFeature/BookOrderViewModel.swift
  App/Sources/Feature/GoalReadingFeature/GoalReadingView.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#56 🔀 :: 독서 상세페이지 퍼블리싱
  App/Sources/DesignSystem/Alert/MindWayAlert.swift
  App/Sources/DesignSystem/Alert/MindWayAlertButtonType.swift
  App/Sources/DesignSystem/Button/MindWayButtonStyle.swift
  App/Sources/DesignSystem/Extensions/View+navigate.swift
  App/Sources/Feature/BookDetailFeature/BookDetailView.swift
  App/Sources/Feature/BookDetailFeature/BookDetailViewModel.swift
  App/Sources/Feature/BookOrderFeature/BookOrderView.swift
  App/Sources/Feature/GoalReadingFeature/Component/SettingGoalReadingView.swift
  App/Sources/Feature/GoalReadingFeature/VIewModel/GoalReadingViewModel.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#58 🔀 :: [#57] Icon 이름 수정
  App/Resources/Icon/Icons.xcassets/exclamationMark.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/exclamationMark.imageset/Frame 9292.svg
  App/Resources/Icon/Icons.xcassets/trash.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/trash.imageset/trash.svg
Labels: 0️⃣Priority: Critical, ⚡️Simple

#64 🔀 :: 도서 수정페이지 퍼블리싱
  App/Sources/DesignSystem/TextField/MindWayTextEditor.swift
  App/Sources/Feature/BookDetailFeature/BookDetailView.swift
  App/Sources/Feature/BookEditFeature/BookEditView.swift
  App/Sources/Feature/BookEditFeature/BookEditViewModel.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#67 🔀 :: 독서 추가 페이지 퍼블리싱
  App/Sources/DesignSystem/TextField/MindWayTextEditor.swift
  App/Sources/Feature/BookDetailFeature/BookDetailView.swift
  App/Sources/Feature/BookPostFeature/BookPostView.swift
  App/Sources/Feature/BookPostFeature/BookPostViewModel.swift
  App/Sources/Feature/EditBookFeature/EditBookView.swift
  App/Sources/Feature/EditBookFeature/EditBookViewModel.swift
  App/Sources/Feature/GoalReadingFeature/GoalReadingView.swift
  App/Sources/Feature/GoalReadingFeature/VIewModel/GoalReadingViewModel.swift
Labels: ✨Feature, 🎨Publishing, 0️⃣Priority: Critical

#62 ♻️ :: 이벤트리스트 Zstack에서 Background로 변경
  App/Sources/Feature/EventFeature/EventTopBarView.swift
Labels: 2️⃣Priority: Medium, ⚡️Simple
